---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        expose: "true"
        app: design-rest
        provider: fabric8
        version: 0.0.8-SNAPSHOT
        group: br.com.luizalabs.designrest
      name: design-rest
    spec:
      ports:
        - nodePort: 30081
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: design-rest
        provider: fabric8
        group: br.com.luizalabs.designrest
      type: LoadBalancer
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: design-rest
        provider: fabric8
        version: 0.0.8-SNAPSHOT
        group: br.com.luizalabs.designrest
      name: design-rest
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: design-rest
          provider: fabric8
          group: br.com.luizalabs.designrest
      template:
        metadata:
          labels:
            app: design-rest
            provider: fabric8
            version: 0.0.8-SNAPSHOT
            group: br.com.luizalabs.designrest
          annotations:
            prometheus.io/scrape: 'true'
            prometheus.io/path: '/actuator/prometheus'
            prometheus.io/port: '8080'
        spec:
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: SPRING_PROFILES_ACTIVE
                  value: develop
                #- name: SERVICES_VEICULO_LEGADO_URL
                #  value: https://dev.apiluiza.com.br/legado/veiculo
              image: diegolirio/design-rest:0.0.8-SNAPSHOT
              imagePullPolicy: Always
              name: design-rest
              securityContext:
                privileged: false