spring:
  profiles: default, develop
  application:
    name: design-rest

services:
  veiculo:
    legado:
      url:  ${SERVICES_VEICULO_LEGADO_URL:https://dev.apiluiza.com.br/legado/veiculo}

pagination:
  offset: 0
  limit: 10

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000